import Head from 'next/head';
import Body from '../components/body/Body';
import Footer from '../components/footer/Footer';
import Header from '../components/header/Header';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google Version 0</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* Header */}
      <Header />

      {/* Body */}
      <Body />

      {/* Footer */}
      <Footer />
    </div>
  );
}
